mongo:
  client_url: mongodb://db:27017
  database_name: laia
openapi:
  file_name: openapi.yaml
backend:
  port: 8000
  folder_name: backend
  jwt_secret_key: secret_key
frontend:
  folder_name: frontend
  backend_base_url: http://localhost:8000
laia:
  llm_model: openai
  logs_conversation_records: true
