version: '3.8'

services:
  laia:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - laia-network
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - laia-network

volumes:
  mongodb-data:
  
networks:
  laia-network:
    driver: bridge